apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: obico
    repo: https://charts.gabe565.com
    version: 0.6.0
    valuesFile: values.yaml
    releaseName: obico
    namespace: obico
    includeCRDs: true
