global:
  security:
    allowInsecureImages: true
server:
  persistence:
    data:
      enabled: true
      retain: false
      storageClass: local-path
      accessMode: ReadWriteOnce
      size: 5Gi
redis:
  image:
    repository: bitnamilegacy/redis
