---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: unpoller
    app.kubernetes.io/name: unpoller
    app.kubernetes.io/version: v2.39.0
  name: unpoller
spec:
  ports:
  - name: http
    port: 9130
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: unpoller
    app.kubernetes.io/name: unpoller
  sessionAffinity: None
  type: ClusterIP
