---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweed-admin
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: seaweed-admin-user
      remoteRef:
        key: "seaweed_admin_user"
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
        nullBytePolicy: Ignore
    - secretKey: seaweed-admin-password
      remoteRef:
        key: "seaweed_admin_password"
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
        nullBytePolicy: Ignore
