podAnnotations:
  use-sha.version-checker.io/manager: "true"
resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
notification:
  enabled: true
  secretName: "tuppr-discord-webhook"
  secretKey: tuppr-discord-webhook
monitoring:
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true
  dashboards:
    enabled: true
    grafanaOperator:
      enabled: true
      allowCrossNamespaceImport: true
      matchLabels:
        dashboards: grafana
