---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 9.4.17
    helm:
      releaseName: cluster
      values: |
        fullnameOverride: argocd
        controller:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
            rules:
              enabled: false
            clusterRoleRules:
              enabled: true
        dex:
          enabled: false
        redis:
          exporter:
            enabled: true
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
            rules:
              enabled: false
            clusterRoleRules:
              enabled: true
        httproute:
          enabled: true
          annotations:
            external-dns.alpha.kubernetes.io/hostname: argocd.vinnysabatini.me
          hostnames:
          - "argocd.vinnysabatini.me"
          parentRefs:
          - name: cluster-gateway
            namespace: kube-system
          rules:
          - matches:
            - path:
                type: PathPrefix
                value: /
            backendRefs:
            - name: argocd-server
              port: 443
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
            rules:
              enabled: false
            clusterRoleRules:
              enabled: true
        repoServer:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
            rules:
              enabled: false
            clusterRoleRules:
              enabled: true
        applicationSet:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
            rules:
              enabled: false
            clusterRoleRules:
              enabled: true
        notifications:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
            rules:
              enabled: false
            clusterRoleRules:
              enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
