---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 9.5.0
    helm:
      releaseName: cluster
      values: |
        fullnameOverride: argocd
        controller:
          vpa:
            enabled: true
            updateMode: "Off"
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
            rules:
              enabled: false
            clusterRoleRules:
              enabled: true
        dex:
          enabled: false
        redis:
          vpa:
            enabled: true
            updateMode: "Off"
          exporter:
            enabled: true
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
            rules:
              enabled: false
            clusterRoleRules:
              enabled: true
        server:
          vpa:
            enabled: true
            updateMode: "Off"
          extraArgs:
          - --insecure # Allow gateway to terminate TLS instead of ArgoCD
          httproute:
            enabled: true
            annotations:
              external-dns.alpha.kubernetes.io/hostname: argocd.vinnysabatini.me
            hostnames:
            - "argocd.vinnysabatini.me"
            parentRefs:
            - group: gateway.networking.k8s.io
              kind: Gateway
              name: cluster-gateway
              namespace: kube-system
            rules:
            - matches:
              - path:
                  type: PathPrefix
                  value: /
              backendRefs:
              - name: argocd-server
                port: 443
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
            rules:
              enabled: false
            clusterRoleRules:
              enabled: true
        repoServer:
          vpa:
            enabled: true
            updateMode: "Off"
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
            rules:
              enabled: false
            clusterRoleRules:
              enabled: true
        applicationSet:
          vpa:
            enabled: true
            updateMode: "Off"
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
            rules:
              enabled: false
            clusterRoleRules:
              enabled: true
        notifications:
          vpa:
            enabled: true
            updateMode: "Off"
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
            rules:
              enabled: false
            clusterRoleRules:
              enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
