---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.20.1
    helm:
      releaseName: cert-manager
      values: |
        config:
          enableGatewayAPI: true
        crds:
          enabled: true
        podAnnotations:
          match-regex.version-checker.io/cert-manager-controller: 'v(\d+)\.(\d+)\.(\d+)'
        cainjector:
          podAnnotations:
            match-regex.version-checker.io/cert-manager-cainjector: 'v(\d+)\.(\d+)\.(\d+)'
        webhook:
          podAnnotations:
            match-regex.version-checker.io/cert-manager-webhook: 'v(\d+)\.(\d+)\.(\d+)'
        extraObjects:
        - |
          apiVersion: autoscaling.k8s.io/v1
          kind: VerticalPodAutoscaler
          metadata:
            labels:
              app.kubernetes.io/instance: cert-manager
              app.kubernetes.io/name: cert-manager
              app.kubernetes.io/part-of: cert-manager
            name: cert-manager
          spec:
            resourcePolicy:
              containerPolicies:
              - containerName: cert-manager-controller
            targetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: cert-manager
            updatePolicy:
              updateMode: "Off"
        - |
          apiVersion: autoscaling.k8s.io/v1
          kind: VerticalPodAutoscaler
          metadata:
            labels:
              app.kubernetes.io/instance: cert-manager-cainjector
              app.kubernetes.io/name: cert-manager-cainjector
              app.kubernetes.io/part-of: cert-manager
            name: cert-manager
          spec:
            resourcePolicy:
              containerPolicies:
              - containerName: cert-manager-cainjector
            targetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: cert-manager
            updatePolicy:
              updateMode: "Off"
        - |
          apiVersion: autoscaling.k8s.io/v1
          kind: VerticalPodAutoscaler
          metadata:
            labels:
              app.kubernetes.io/instance: cert-manager-webhook
              app.kubernetes.io/name: cert-manager-webhook
              app.kubernetes.io/part-of: cert-manager
            name: cert-manager-webhook
          spec:
            resourcePolicy:
              containerPolicies:
              - containerName: cert-manager-webhook
            targetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: cert-manager-webhook
            updatePolicy:
              updateMode: "Off"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
