---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: v2.2.0
    helm:
      releaseName: external-secrets
      values: |
        bitwarden-sdk-server:
          enabled: true
        webhook:
          lookaheadInterval: "210h"
          certManager:
            enabled: true
            cert:
              issuerRef:
                group: cert-manager.io
                kind: Issuer
                name: bitwarden-certificate-issuer
        extraObjects:
        - apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: bitwarden-bootstrap-certificate
          spec:
            # this is discouraged but required by ios
            commonName: cert-manager-bitwarden-tls
            isCA: true
            secretName: bitwarden-tls-certs
            subject:
              organizations:
                - external-secrets.io
            dnsNames:
              - external-secrets-bitwarden-sdk-server.external-secrets.svc.cluster.local
              - bitwarden-sdk-server.external-secrets.svc.cluster.local
              - localhost
            ipAddresses:
              - 127.0.0.1
              - ::1
            privateKey:
              algorithm: RSA
              encoding: PKCS8
              size: 2048
            issuerRef:
              name: bitwarden-bootstrap-issuer
              kind: Issuer
              group: cert-manager.io
        - apiVersion: external-secrets.io/v1
          kind: ClusterSecretStore
          metadata:
            name: bitwarden-secretsmanager
          spec:
            provider:
              bitwardensecretsmanager:
                apiURL: https://vault.bitwarden.com/api
                identityURL: https://vault.bitwarden.com/identity
                auth:
                  secretRef:
                    credentials:
                      key: token
                      name: bitwarden-access-token
                      namespace: external-secrets
                bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
                caProvider:
                  key: tls.crt
                  name: bitwarden-tls-certs
                  namespace: external-secrets
                  type: Secret
                organizationID: a73df6d1-1f9a-4d31-8e29-b3d00034aa3c
                projectID: a14dc1a8-cfd6-49e9-a517-b3d00035cbaa
        - apiVersion: cert-manager.io/v1
          kind: Issuer
          metadata:
            name: bitwarden-bootstrap-issuer
          spec:
            selfSigned: {}
        - apiVersion: cert-manager.io/v1
          kind: Issuer
          metadata:
            name: bitwarden-certificate-issuer
          spec:
            ca:
              secretName: bitwarden-tls-certs
        - apiVersion: autoscaling.k8s.io/v1
          kind: VerticalPodAutoscaler
          metadata:
            labels:
              app.kubernetes.io/instance: external-secrets
              app.kubernetes.io/name: external-secrets
            name: external-secrets
          spec:
            resourcePolicy:
              containerPolicies:
              - containerName: external-secrets
            targetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: external-secrets
            updatePolicy:
              updateMode: "Off"
        - apiVersion: autoscaling.k8s.io/v1
          kind: VerticalPodAutoscaler
          metadata:
            labels:
              app.kubernetes.io/instance: external-secrets-webhook
              app.kubernetes.io/name: external-secrets-webhook
            name: external-secrets-webhook
          spec:
            resourcePolicy:
              containerPolicies:
              - containerName: webhook
            targetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: external-secrets-webhook
            updatePolicy:
              updateMode: "Off"
        - apiVersion: autoscaling.k8s.io/v1
          kind: VerticalPodAutoscaler
          metadata:
            labels:
              app.kubernetes.io/instance: bitwarden-sdk-server
              app.kubernetes.io/name: bitwarden-sdk-server
            name: bitwarden-sdk-server
          spec:
            resourcePolicy:
              containerPolicies:
              - containerName: bitwarden-sdk-server
            targetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: bitwarden-sdk-server
            updatePolicy:
              updateMode: "Off"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
