---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: grafana-operator
    repoURL: ghcr.io/grafana/helm-charts
    targetRevision: v5.17.1
    helm:
      releaseName: grafana-operator
      values: |
        dashboard:
          enabled: true
        serviceMonitor:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
