---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: headlamp
    repoURL: https://kubernetes-sigs.github.io/headlamp/
    targetRevision: 0.41.0
    helm:
      releaseName: headlamp
      values: |
        httpRoute:
          enabled: true
          annotations:
            external-dns.alpha.kubernetes.io/hostname: headlamp.vinnysabatini.me
          hostnames:
          - headlamp.vinnysabatini.me
          parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: cluster-gateway
            namespace: kube-system
          rules:
          - matches:
            - path:
                type: PathPrefix
                value: /
            backendRefs:
            - name: headlamp
              port: 80
        env:
        - name: HEADLAMP_CONFIG_METRICS_ENABLED
          value: "true"
        extraManifests:
        - |
          apiVersion: monitoring.coreos.com/v1
          kind: ServiceMonitor
          metadata:
            labels:
              app.kubernetes.io/managed-by: Helm
              app.kubernetes.io/name: headlamp
              app.kubernetes.io/instance: headlamp
            name: headlamp
          spec:
            endpoints:
            - honorLabels: false
              interval: 30s
              path: /metrics
              port: http
            namespaceSelector:
              matchNames:
              - headlamp
            selector:
              matchLabels:
                app.kubernetes.io/instance: headlamp
                app.kubernetes.io/name: headlamp
  destination:
    server: "https://kubernetes.default.svc"
    namespace: headlamp
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
