---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.19.0
    helm:
      releaseName: keda
      values: |
        prometheus:
          metricServer:
            enabled: true
            serviceMonitor:
              enabled: true
          operator:
            enabled: true
            serviceMonitor:
              enabled: true
          webhooks:
            enabled: true
            serviceMonitor:
              enabled: true
        certificates:
          certManager:
            enabled: true
            issuer:
              generate: true
        extraObjects:
        - apiVersion: autoscaling.k8s.io/v1
          kind: VerticalPodAutoscaler
          metadata:
            labels:
              app.kubernetes.io/instance: keda-operator
              app.kubernetes.io/name: keda-operator
            name: keda-operator
          spec:
            resourcePolicy:
              containerPolicies:
              - containerName: keda-operator
            targetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: keda-operator
            updatePolicy:
              updateMode: "Off"
        - apiVersion: autoscaling.k8s.io/v1
          kind: VerticalPodAutoscaler
          metadata:
            labels:
              app.kubernetes.io/instance: keda-admission-webhooks
              app.kubernetes.io/name: keda-admission-webhooks
            name: keda-admission-webhooks
          spec:
            resourcePolicy:
              containerPolicies:
              - containerName: keda-admission-webhooks
            targetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: keda-admission-webhooks
            updatePolicy:
              updateMode: "Off"
        - apiVersion: autoscaling.k8s.io/v1
          kind: VerticalPodAutoscaler
          metadata:
            labels:
              app.kubernetes.io/instance: keda-operator-metrics-apiserver
              app.kubernetes.io/name: keda-operator-metrics-apiserver
            name: keda-operator-metrics-apiserver
          spec:
            resourcePolicy:
              containerPolicies:
              - containerName: keda-operator-metrics-apiserver
            targetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: keda-operator-metrics-apiserver
            updatePolicy:
              updateMode: "Off"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keda
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
