---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kube-state-metrics
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 7.2.2
    helm:
      releaseName: crd
      values: |
        prometheus:
          monitor:
            enabled: true
        verticalPodAutoscaler:
          enabled: true
          updatePolicy:
            updateMode: "Off"
        rbac:
          extraRules:
            - apiGroups: ["autoscaling.k8s.io"]
              resources: ["verticalpodautoscalers"]
              verbs: ["list", "watch"]
        customResourceState:
          enabled: true
          create: true
          config:
            kind: CustomResourceStateMetrics
            spec:
              resources:
                - groupVersionKind:
                    group: autoscaling.k8s.io
                    kind: "VerticalPodAutoscaler"
                    version: "v1"
                  labelsFromPath:
                    namespace: [metadata, namespace]
                    target_api_version: [spec, targetRef, apiVersion]
                    target_kind: [spec, targetRef, kind]
                    target_name: [spec, targetRef, name]
                    verticalpodautoscaler: [metadata, name]
                  metricNamePrefix: "kube"
                  metrics:
                    # kube_verticalpodautoscaler_annotations
                    - name: "verticalpodautoscaler_annotations"
                      help: "Kubernetes annotations converted to Prometheus labels."
                      each:
                        type: Info
                        info:
                          labelsFromPath:
                            annotation_*: [metadata, annotations]
                            name: [metadata, name]
                    # kube_verticalpodautoscaler_labels
                    - name: "verticalpodautoscaler_labels"
                      help: "Kubernetes labels converted to Prometheus labels."
                      each:
                        type: Info
                        info:
                          labelsFromPath:
                            label_*: [metadata, labels]
                            name: [metadata, name]
                    # kube_verticalpodautoscaler_spec_updatepolicy_updatemode
                    - name: "verticalpodautoscaler_spec_updatepolicy_updatemode"
                      help: "Update mode of the VerticalPodAutoscaler."
                      each:
                        type: StateSet
                        stateSet:
                          labelName: "update_mode"
                          path: [spec, updatePolicy, updateMode]
                          list: ["Auto", "Initial", "Off", "Recreate"]
                    # Memory kube_verticalpodautoscaler_spec_resourcepolicy_container_policies_minallowed_memory
                    - name: "verticalpodautoscaler_spec_resourcepolicy_container_policies_minallowed_memory"
                      help: "Minimum memory resources the VerticalPodAutoscaler can set for containers matching the name."
                      commonLabels:
                        unit: "byte"
                        resource: "memory"
                      each:
                        type: Gauge
                        gauge:
                          path: [spec, resourcePolicy, containerPolicies]
                          labelsFromPath:
                            container: [containerName]
                          valueFrom: [minAllowed, memory]
                    # CPU kube_verticalpodautoscaler_spec_resourcepolicy_container_policies_minallowed_cpu
                    - name: "verticalpodautoscaler_spec_resourcepolicy_container_policies_minallowed_cpu"
                      help: "Minimum cpu resources the VerticalPodAutoscaler can set for containers matching the name."
                      commonLabels:
                        unit: "core"
                        resource: "cpu"
                      each:
                        type: Gauge
                        gauge:
                          path: [spec, resourcePolicy, containerPolicies]
                          labelsFromPath:
                            container: [containerName]
                          valueFrom: [minAllowed, cpu]
                    # Memory kube_verticalpodautoscaler_spec_resourcepolicy_container_policies_maxallowed_memory
                    - name: "verticalpodautoscaler_spec_resourcepolicy_container_policies_maxallowed_memory"
                      help: "Maximum memory resources the VerticalPodAutoscaler can set for containers matching the name."
                      commonLabels:
                        unit: "byte"
                        resource: "memory"
                      each:
                        type: Gauge
                        gauge:
                          path: [spec, resourcePolicy, containerPolicies]
                          labelsFromPath:
                            container: [containerName]
                          valueFrom: [maxAllowed, memory]
                    # CPU kube_verticalpodautoscaler_spec_resourcepolicy_container_policies_maxallowed_cpu
                    - name: "verticalpodautoscaler_spec_resourcepolicy_container_policies_maxallowed_cpu"
                      help: "Maximum cpu resources the VerticalPodAutoscaler can set for containers matching the name."
                      commonLabels:
                        unit: "core"
                        resource: "cpu"
                      each:
                        type: Gauge
                        gauge:
                          path: [spec, resourcePolicy, containerPolicies]
                          labelsFromPath:
                            container: [containerName]
                          valueFrom: [maxAllowed, cpu]
                    # Memory kube_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound_memory
                    - name: "verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound_memory"
                      help: "Minimum memory resources the container can use before the VerticalPodAutoscaler updater evicts it."
                      commonLabels:
                        unit: "byte"
                        resource: "memory"
                      each:
                        type: Gauge
                        gauge:
                          path: [status, recommendation, containerRecommendations]
                          labelsFromPath:
                            container: [containerName]
                          valueFrom: [lowerBound, memory]
                    # CPU kube_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound_cpu
                    - name: "verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound_cpu"
                      help: "Minimum cpu resources the container can use before the VerticalPodAutoscaler updater evicts it."
                      commonLabels:
                        unit: "core"
                        resource: "cpu"
                      each:
                        type: Gauge
                        gauge:
                          path: [status, recommendation, containerRecommendations]
                          labelsFromPath:
                            container: [containerName]
                          valueFrom: [lowerBound, cpu]
                    # Memory kube_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound_memory
                    - name: "verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound_memory"
                      help: "Maximum memory resources the container can use before the VerticalPodAutoscaler updater evicts it."
                      commonLabels:
                        unit: "byte"
                        resource: "memory"
                      each:
                        type: Gauge
                        gauge:
                          path: [status, recommendation, containerRecommendations]
                          labelsFromPath:
                            container: [containerName]
                          valueFrom: [upperBound, memory]
                    # CPU kube_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound_cpu
                    - name: "verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound_cpu"
                      help: "Maximum cpu resources the container can use before the VerticalPodAutoscaler updater evicts it."
                      commonLabels:
                        unit: "core"
                        resource: "cpu"
                      each:
                        type: Gauge
                        gauge:
                          path: [status, recommendation, containerRecommendations]
                          labelsFromPath:
                            container: [containerName]
                          valueFrom: [upperBound, cpu]
                    # Memory kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target_memory
                    - name: "verticalpodautoscaler_status_recommendation_containerrecommendations_target_memory"
                      help: "Target memory resources the VerticalPodAutoscaler recommends for the container."
                      commonLabels:
                        unit: "byte"
                        resource: "memory"
                      each:
                        type: Gauge
                        gauge:
                          path: [status, recommendation, containerRecommendations]
                          labelsFromPath:
                            container: [containerName]
                          valueFrom: [target, memory]
                    # CPU kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target_cpu
                    - name: "verticalpodautoscaler_status_recommendation_containerrecommendations_target_cpu"
                      help: "Target cpu resources the VerticalPodAutoscaler recommends for the container."
                      commonLabels:
                        unit: "core"
                        resource: "cpu"
                      each:
                        type: Gauge
                        gauge:
                          path: [status, recommendation, containerRecommendations]
                          labelsFromPath:
                            container: [containerName]
                          valueFrom: [target, cpu]
                    # Memory kube_verticalpodautoscaler_status_recommendation_containerrecommendations_uncappedtarget_memory
                    - name: "verticalpodautoscaler_status_recommendation_containerrecommendations_uncappedtarget_memory"
                      help: "Target memory resources the VerticalPodAutoscaler recommends for the container ignoring bounds."
                      commonLabels:
                        unit: "byte"
                        resource: "memory"
                      each:
                        type: Gauge
                        gauge:
                          path: [status, recommendation, containerRecommendations]
                          labelsFromPath:
                            container: [containerName]
                          valueFrom: [uncappedTarget, memory]
                    # CPU kube_verticalpodautoscaler_status_recommendation_containerrecommendations_uncappedtarget_cpu
                    - name: "verticalpodautoscaler_status_recommendation_containerrecommendations_uncappedtarget_cpu"
                      help: "Target memory resources the VerticalPodAutoscaler recommends for the container ignoring bounds."
                      commonLabels:
                        unit: "core"
                        resource: "cpu"
                      each:
                        type: Gauge
                        gauge:
                          path: [status, recommendation, containerRecommendations]
                          labelsFromPath:
                            container: [containerName]
                          valueFrom: [uncappedTarget, cpu]
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
