---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: additional-deployments/kubevirt
    repoURL: https://github.com/vinny-sabatini/homelab.git
    targetRevision: main
  destination:
    namespace: kubevirt
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        kubevirt.io: ""
        pod-security.kubernetes.io/enforce: "privileged"
