apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- alloy/application.yaml
- argocd.yaml
- bambuddy/application.yaml
- bambulab-metrics-explorer/application.yaml
- cert-manager/application.yaml
- cilium.yaml
- cluster-configs.yaml
- external-dns-configs.yaml
- external-dns.yaml
- external-secrets.yaml
- gateway-crds.yaml
- grafana/application.yaml
- headlamp/application.yaml
- keda/application.yaml
- kepler/application.yaml
- kubelet-serving-cert-approver.yaml
- kube-prometheus.yaml
- kube-state-metrics/application.yaml
- lennox-prometheus-exporter/application.yaml
- local-path-provisioner.yaml
- loki/application.yaml
- metrics-server/application.yaml
- obico.yaml
- prometheus-blackbox-exporter/application.yaml
- renovate-operator.yaml
- tuppr.yaml
- unpoller/application.yaml
- version-checker/application.yaml
- vertical-pod-autoscaler/application.yaml
