---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obico
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: obico
    repoURL: oci://ghcr.io/gabe565/charts/obico
    targetRevision: 0.6.0
    helm:
      releaseName: obico
      values: |
        global:
          security:
            allowInsecureImages: true
        server:
          persistence:
            data:
              enabled: true
              retain: false
              storageClass: local-path
              accessMode: ReadWriteOnce
              size: 5Gi
        redis:
          image:
            repository: bitnamilegacy/redis
  destination:
    server: "https://kubernetes.default.svc"
    namespace: obico
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
