---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: renovate
    repoURL: oci://ghcr.io/renovatebot/charts/renovate
    targetRevision: 46.245.1
    helm:
      releaseName: renovate
      values: |
        existingSecret: renovate-token
        renovate:
          config: |
            {
              "repositories": ["vinny-sabatini/homelab"],
              "platform": "github",
              "autodiscover": "false",
              "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
              "enabledManagers": ["argocd"],
              "argocd": {
                "managerFilePatterns": ["applications/*"]
              },
              "packageRules": [
                {
                  "matchManagers": ["argocd"],
                  "matchFileNames": [
                    "applications/tuppr.yaml"
                  ],
                  "overridePackageName": "ghcr.io/home-operations/charts/tuppr"
                }
                {
                  "matchManagers": ["argocd"],
                  "matchFileNames": [
                    "applications/kepler.yaml"
                  ],
                  "overridePackageName": "quay.io/sustainable_computing_io/charts/kepler"
                }
              ]
            }
        extraObjects:
        - |
          apiVersion: external-secrets.io/v1
          kind: ExternalSecret
          metadata:
            name: renovate-token
          spec:
            refreshInterval: 1h0m0s
            secretStoreRef:
              name: bitwarden-secretsmanager
              kind: ClusterSecretStore
            data:
              - secretKey: RENOVATE_TOKEN
                remoteRef:
                  key: "renovate_token"
                  metadataPolicy: None
                  decodingStrategy: None
                  conversionStrategy: Default
                  nullBytePolicy: Ignore
  destination:
    server: "https://kubernetes.default.svc"
    namespace: renovate
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
