---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelet-serving-cert-approver
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: applications/kubelet-serving-cert-approver
    repoURL: 'https://github.com/vinny-sabatini/homelab.git'
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubelet-serving-cert-approver
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
