---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bambuddy
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: applications/bambuddy
    repoURL: 'https://github.com/vinny-sabatini/homelab.git'
    targetRevision: kustomize-refactor
  destination:
    server: "https://kubernetes.default.svc"
    namespace: bambuddy
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: "privileged"
