---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-prometheus
  namespace: home-assistant
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: home_assistant_prometheus
      remoteRef:
        key: "home_assistant_prometheus"
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
        nullBytePolicy: Ignore
