apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: seaweedfs-csi-driver
    repo: https://seaweedfs.github.io/seaweedfs/helm
    version: 0.2.40
    valuesFile: values.yaml
    releaseName: seaweedfs-csi-driver
    namespace: seaweedfs
