---
# Based on https://grafana.com/api/dashboards/15141/revisions/1/download
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-dashboards
  namespace: monitoring
data:
  dashboard.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "datasource",
              "uid": "grafana"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "description": "Logs collected from Kubernetes, stored in Loki",
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 6,
      "links": [],
      "panels": [
        {
          "datasource": {
            "type": "loki",
            "uid": "ef74c9dc-6896-42bc-86af-259e647a462b"
          },
          "description": "",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "barWidthFactor": 0.6,
                "drawStyle": "bars",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 4,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 4,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": false
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "pluginVersion": "11.3.0",
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "uid": "ef74c9dc-6896-42bc-86af-259e647a462b"
              },
              "expr": "sum(count_over_time({namespace=~\"$namespace\", stream=~\"$stream\", container =~\"$container\"} |= \"$query\" [$__interval]))",
              "instant": false,
              "legendFormat": "Log count",
              "range": true,
              "refId": "A"
            }
          ],
          "title": "",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "loki",
            "uid": "ef74c9dc-6896-42bc-86af-259e647a462b"
          },
          "description": "Logs from services running in Kubernetes",
          "fieldConfig": {
            "defaults": {},
            "overrides": []
          },
          "gridPos": {
            "h": 25,
            "w": 24,
            "x": 0,
            "y": 4
          },
          "id": 2,
          "options": {
            "dedupStrategy": "none",
            "enableLogDetails": true,
            "prettifyLogMessage": false,
            "showCommonLabels": false,
            "showLabels": false,
            "showTime": false,
            "sortOrder": "Descending",
            "wrapLogMessage": false
          },
          "pluginVersion": "11.3.0",
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "uid": "ef74c9dc-6896-42bc-86af-259e647a462b"
              },
              "editorMode": "code",
              "expr": "{namespace=~\"$namespace\", stream=~\"$stream\", container =~\"$container\"} |= \"$query\"",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "",
          "transformations": [
            {
              "id": "extractFields",
              "options": {
                "format": "json",
                "jsonPaths": [
                  {
                    "path": "message"
                  },
                  {
                    "path": ""
                  }
                ],
                "keepTime": false,
                "replace": false,
                "source": "Line"
              }
            },
            {
              "id": "organize",
              "options": {
                "excludeByName": {
                  "Line": false,
                  "id": false,
                  "labelTypes": false,
                  "tsNs": false
                },
                "includeByName": {},
                "indexByName": {
                  "Line": 3,
                  "Time": 2,
                  "id": 6,
                  "labelTypes": 5,
                  "labels": 1,
                  "message": 0,
                  "tsNs": 4
                },
                "renameByName": {}
              }
            }
          ],
          "type": "logs"
        }
      ],
      "preload": false,
      "refresh": false,
      "schemaVersion": 40,
      "tags": [],
      "templating": {
        "list": [
          {
            "current": {
              "text": "",
              "value": ""
            },
            "description": "String to search for",
            "label": "Search Query",
            "name": "query",
            "options": [
              {
                "selected": true,
                "text": "",
                "value": ""
              }
            ],
            "query": "",
            "type": "textbox"
          },
          {
            "allValue": ".+",
            "current": {
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "datasource": "loki",
            "definition": "label_values(namespace)",
            "includeAll": true,
            "multi": true,
            "name": "namespace",
            "options": [],
            "query": "label_values(namespace)",
            "refresh": 1,
            "regex": "",
            "type": "query"
          },
          {
            "allValue": ".+",
            "current": {
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "datasource": "loki",
            "definition": "label_values(stream)",
            "includeAll": true,
            "multi": true,
            "name": "stream",
            "options": [],
            "query": "label_values(stream)",
            "refresh": 1,
            "regex": "",
            "type": "query"
          },
          {
            "allValue": ".+",
            "current": {
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "datasource": "loki",
            "definition": "label_values(container)",
            "includeAll": true,
            "multi": true,
            "name": "container",
            "options": [],
            "query": "label_values(container)",
            "refresh": 1,
            "regex": "",
            "type": "query"
          }
        ]
      },
      "time": {
        "from": "now-30m",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Loki dashboard",
      "uid": "depk7hz3t8n40d",
      "version": 3,
      "weekStart": ""
    }
