---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: tempo
  namespace: monitoring
spec:
  datasource:
    access: proxy
    type: tempo
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
      lokiSearch:
        datasourceUid: 'loki'
      serviceMap:
        datasourceUid: 'prometheus'
      tracesToProfiles:
        datasourceUid: 'pyroscope'
      nodeGraph:
        enabled: true
    name: tempo
    url: http://tempo-query-frontend.tempo.svc.cluster.local:3200
    orgId: 1
  instanceSelector:
    matchLabels:
      dashboards: grafana
