---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki
  namespace: monitoring
spec:
  datasource:
    access: proxy
    type: loki
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
    name: loki
    url: http://loki-gateway.loki.svc.cluster.local:80
    orgId: 1
  instanceSelector:
    matchLabels:
      dashboards: grafana
  uid: ef74c9dc-6896-42bc-86af-259e647a462b
