---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
  namespace: monitoring
spec:
  datasource:
    access: proxy
    type: prometheus
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
    name: prometheus
    url: http://kube-prom-prometheus.monitoring:9090
  instanceSelector:
    matchLabels:
      dashboards: grafana
