---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  deployment:
    spec:
      template:
        metadata:
          annotations:
            match-regex.version-checker.io/grafana: '(\d+)\.(\d+)\.(\d+)'
  service:
    spec:
      loadBalancerClass: io.cilium/l2-announcer
      type: LoadBalancer
  config:
    log:
      mode: "console"
