---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  service:
    spec:
      loadBalancerClass: io.cilium/l2-announcer
      type: LoadBalancer
  config:
    log:
      mode: "console"
