---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tuppr-discord-webhook
  namespace: system-upgrade
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: tuppr-discord-webhook
      remoteRef:
        key: "tuppr_discord_webhook"
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
        nullBytePolicy: Ignore
