---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: version-checker
  namespace: version-checker
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: ghcr-token
      remoteRef:
        key: "version_checker_ghcr"
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
    - secretKey: docker-token
      remoteRef:
        key: "version_checker_docker"
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
