apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ExternalSecret-unifi.yaml
- verticalpodautoscaler.yaml

helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    version: 1.21.1
    valuesFile: values.yaml
    namespace: external-dns
    releaseName: external-dns
    includeCRDs: true
