---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  monitorNamespace: monitoring
  monitorAccount: cluster-kube-prometheus-st-operator
  customizeComponents: {}
  configuration:
    developerConfiguration:
      featureGates: []
    smbios:
      sku: "TalosCloud"
      version: "v0.1.0"
      manufacturer: "Talos Virtualization"
      product: "talosvm"
      family: "ccio"
  # workloadUpdateStrategy:
  #   workloadUpdateMethods:
  #   - LiveMigrate # enable if you have deployed either Longhorn or NFS-CSI for shared storage.
