---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.com/api
      identityURL: https://vault.bitwarden.com/identity
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        key: tls.crt
        name: bitwarden-tls-certs
        namespace: external-secrets
        type: Secret
      organizationID: a73df6d1-1f9a-4d31-8e29-b3d00034aa3c
      projectID: a14dc1a8-cfd6-49e9-a517-b3d00035cbaa
