---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/instance: bitwarden-sdk-server
    app.kubernetes.io/name: bitwarden-sdk-server
  name: bitwarden-sdk-server
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: bitwarden-sdk-server
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bitwarden-sdk-server
  updatePolicy:
    updateMode: "Off"
