---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: argocd-admin
  namespace: argocd
spec:
  refreshInterval: 1h0m0s
  secretStoreRefs:
    - name: bitwarden-secretsmanager
      kind: ClusterSecretStore
  selector:
    secret:
      name: argocd-initial-admin-secret
  data:
    - conversionStrategy: None
      match:
        secretKey: password
        remoteRef:
          remoteKey: argocd_admin
      metadata:
        note: "ArgoCD admin password"
