---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h0m0s
  secretStoreRefs:
    - name: bitwarden-secretsmanager
      kind: ClusterSecretStore
  selector:
    secret:
      name: grafana-admin-credentials
  data:
    - conversionStrategy: None
      match:
        secretKey: GF_SECURITY_ADMIN_PASSWORD
        remoteRef:
          remoteKey: grafana_admin
      metadata:
        note: "Grafana admin password"
