---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: pyroscope
  namespace: monitoring
spec:
  datasource:
    access: proxy
    type: phlare
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
    name: pyroscope
    url: http://pyroscope.pyroscope.svc.cluster.local:4040
    orgId: 1
  instanceSelector:
    matchLabels:
      dashboards: grafana
