---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: tempo
  namespace: monitoring
spec:
  datasource:
    access: proxy
    type: tempo
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
      tracesToMetrics:
        datasourceUid: 'prometheus'
        queries:
          - name: 'Request Rate'
            query: 'sum(rate(http_server_requests_total{$$__tags}[5m]))'
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['job', 'instance', 'pod', 'service.name']
      tracesToProfiles:
        datasourceUid: 'pyroscope'
      nodeGraph:
        enabled: true
    name: tempo
    url: http://tempo-query-frontend.tempo.svc.cluster.local:3200
    orgId: 1
  instanceSelector:
    matchLabels:
      dashboards: grafana
