---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-viewer
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-viewer
subjects:
- kind: ServiceAccount
  name: vector
  namespace: vector
roleRef:
  kind: ClusterRole
  name: vector-viewer
  apiGroup: rbac.authorization.k8s.io
