---
machine:
  logging:
    destinations:
      - endpoint: tcp://alloy.alloy.svc:12346/
        format: "json_lines"
---
apiVersion: v1alpha1
kind: KmsgLogConfig
name: remote-log
url: tcp://alloy.alloy.svc:12347/
