apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: music-assistant
    repo: ghcr.io/toanju/helm-charts
    version: 2.10.4
    valuesFile: values.yaml
    releaseName: music-assistant
    namespace: music-assistant
