{
 "title": "bambulabs-exporter",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Instant Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Remaining Time on Print",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(mc_remaining_time)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hotbed Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(bed_temper)", "legendFormat": "__auto" },
    { "expr": "max(bed_target_temper)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Chamber Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(abs(chamber_temper))", "legendFormat": "__auto" },
    {}
   ]
  },
  {
   "title": "Print Percentage Remaining",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(mc_percent)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nozzle Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(nozzle_temper)", "legendFormat": "__auto" },
    { "expr": "max(nozzle_target_temper)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AMS Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(abs(ams_temp))", "legendFormat": "__auto" },
    {}
   ]
  },
  { "title": "Print Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Remaining Time on Print",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    { "expr": "max(mc_remaining_time)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Print Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 14 },
   "targets": [
    { "expr": "max(print_error)", "legendFormat": "__auto" },
    { "expr": "max(fail_reason)", "legendFormat": "__auto" },
    { "expr": "max(mc_print_error_code)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MC Print Stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 22 },
   "targets": [
    { "expr": "max(mc_print_sub_stage)", "legendFormat": "__auto" },
    { "expr": "max(mc_print_stage)", "legendFormat": "__auto" }
   ]
  },
  { "title": "System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Nozzle Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "max(nozzle_temper)", "legendFormat": "__auto" },
    { "expr": "max(nozzle_target_temper)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AMS, Bed, & Chamber Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "max(ams_temp)", "legendFormat": "__auto" },
    { "expr": "max(bed_temper)", "legendFormat": "__auto" },
    { "expr": "max(chamber_temper)", "legendFormat": "__auto" },
    { "expr": "max(nozzle_temper)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fan Speeds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    { "expr": "max(big_fan1_speed)", "legendFormat": "__auto" },
    { "expr": "max(big_fan2_speed)", "legendFormat": "__auto" },
    {},
    { "expr": "max(cooling_fan_speed)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fan Gear Metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    { "expr": "max(fan_gear)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "WiFi SIgnal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    { "expr": "max(wifi_signal)", "legendFormat": "__auto" }
   ]
  }
 ]
}