---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: bambulab-metrics-exporter
    app.kubernetes.io/name: bambulab-metrics-exporter
    app.kubernetes.io/version: 0.1.40
  name: bambulab-metrics-exporter
