---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matter-server
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: applications/matter-server
    repoURL: 'https://github.com/vinny-sabatini/homelab.git'
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: matter-server
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
