apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: vertical-pod-autoscaler
    repo: https://kubernetes.github.io/autoscaler
    version: 0.11.0
    valuesFile: values.yaml
    namespace: vertical-pod-autoscaler
    releaseName: vertical-pod-autoscaler
    includeCRDs: true
