---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: bambu-exporter
    app.kubernetes.io/name: bambu-exporter
    app.kubernetes.io/version: 1.5.0
  name: bambu-exporter
spec:
  ports:
  - name: http
    port: 9101
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: bambu-exporter
    app.kubernetes.io/name: bambu-exporter
  sessionAffinity: None
  type: ClusterIP
