---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: bambu-exporter
    app.kubernetes.io/name: bambu-exporter
    app.kubernetes.io/version: 1.5.0
  name: bambu-exporter
