---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: bambu-exporter
    app.kubernetes.io/name: bambu-exporter
  name: bambu-exporter
spec:
  endpoints:
  - port: http
    scheme: http
    path: /metrics
  namespaceSelector:
    matchNames:
    - bambu-exporter
  selector:
    matchLabels:
      app.kubernetes.io/instance: bambu-exporter
      app.kubernetes.io/name: bambu-exporter
