---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: global-alertmanager-configuration
spec:
  route:
    groupBy: ['alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'discord'
    routes:
    - receiver: 'null'
      matchers:
        - name: 'alertname'
          matchType: "="
          value: "Watchdog"
  receivers:
  - name: 'null'
  - name: 'discord'
    discordConfigs:
    - apiURL:
        key: discord-webhook
        name: discord-webhook
      username: prometheus
      avatarURL: https://github.com/NX211/homer-icons/blob/master/png/prometheus.png?raw=true
