---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bambulab-metrics-explorer-config
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
