---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: bambulab-metrics-explorer
    app.kubernetes.io/name: bambulab-metrics-explorer
    app.kubernetes.io/version: 0.1.40
  name: bambulab-metrics-explorer
spec:
  ports:
  - name: http
    port: 9109
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: bambulab-metrics-explorer
    app.kubernetes.io/name: bambulab-metrics-explorer
  sessionAffinity: None
  type: ClusterIP
