---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: bambulab-metrics-explorer
    app.kubernetes.io/name: bambulab-metrics-explorer
  name: bambulab-metrics-explorer
spec:
  endpoints:
  - port: http
    scheme: http
    path: /metrics
  namespaceSelector:
    matchNames:
    - bambulab-metrics-explorer
  selector:
    matchLabels:
      app.kubernetes.io/instance: bambulab-metrics-explorer
      app.kubernetes.io/name: bambulab-metrics-explorer
